# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pheaa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pheaa
  pod 'AppCenter/Crashes', '~> 1.8.0'
  pod 'AppCenter/Analytics', '~> 1.8.0'
  pod 'AppCenterReactNativeShared', '~> 1.7.1'

  

  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

end
