# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "d92326d4-cd2f-449c-a3a4-90e989baed60"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
   increment_build_number

  # build your iOS app
  build_app(
    # scheme: "YourScheme",
    export_method: "ad-hoc"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    # api_token: "YOUR_API_KEY",
    # build_secret: "YOUR_BUILD_SECRET"
  )
end


lane :codeSign do
  cert(
    username: "john.amuesi@wipro.com"
  )
  sigh(
    force: true,
    username: "john.amuesi@wipro.com",
    app_identifier: "com.sarchitech.pheaa"
  )
end